2020-04-10 20:34:48,409 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-04-10 20:48:50,950 - messages - ERROR - Something wrong
Traceback (most recent call last):
  File "/root/LaBot/LaBot/messages.py", line 45, in save
    file.download(new_path)
  File "/usr/local/lib/python3.6/dist-packages/telegram/files/file.py", line 142, in download
    with open(filename, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ba/Documents/LaBot/labs/lab_9/krestenko_9.pdf'
2020-04-10 20:48:55,553 - messages - ERROR - Something wrong
Traceback (most recent call last):
  File "/root/LaBot/LaBot/messages.py", line 45, in save
    file.download(new_path)
  File "/usr/local/lib/python3.6/dist-packages/telegram/files/file.py", line 142, in download
    with open(filename, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ba/Documents/LaBot/labs/lab_9/krestenko_9.zip'
2020-04-10 20:49:14,034 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-04-10 20:49:15,327 - telegram.ext.updater - WARNING - Exiting immediately!
2020-04-10 20:51:11,526 - messages - INFO - Recieved file krestenko_9.pdf from chat 222511256
2020-04-10 20:51:11,724 - messages - ERROR - Something wrong
Traceback (most recent call last):
  File "/root/LaBot/LaBot/messages.py", line 49, in save
    file.download(new_path)
  File "/usr/local/lib/python3.6/dist-packages/telegram/files/file.py", line 142, in download
    with open(filename, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'LaBot/labs/lab_9/krestenko_9.pdf'
2020-04-10 20:51:22,128 - messages - INFO - Recieved file krestenko_9.pdf from chat 222511256
2020-04-10 20:51:22,337 - messages - ERROR - Something wrong
Traceback (most recent call last):
  File "/root/LaBot/LaBot/messages.py", line 49, in save
    file.download(new_path)
  File "/usr/local/lib/python3.6/dist-packages/telegram/files/file.py", line 142, in download
    with open(filename, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'LaBot/labs/lab_9/krestenko_9.pdf'
2020-04-10 20:51:38,429 - messages - INFO - Recieved file krestenko_9.zip from chat 222511256
2020-04-10 20:51:38,614 - messages - ERROR - Something wrong
Traceback (most recent call last):
  File "/root/LaBot/LaBot/messages.py", line 49, in save
    file.download(new_path)
  File "/usr/local/lib/python3.6/dist-packages/telegram/files/file.py", line 142, in download
    with open(filename, 'wb') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: 'LaBot/labs/lab_9/krestenko_9.zip'
2020-04-10 20:52:07,630 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
